### ISSUE TITLE
Starting crash

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#112]
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [delete from `crowdcontrol`.`Algorithm_Rating_Quality_Param` where (`crowdcontrol`.`Algorithm_Rating_Quality_Param`.`algorithm` = ? and 1 = 1)]; Cannot delete or update a parent row: a foreign key constraint fails (`crowdcontrol`.`Chosen_Rating_Quality_Param`, CONSTRAINT `chosenRatingQualityParam` FOREIGN KEY (`param`) REFERENCES `Algorithm_Rating_Quality_Param` (`id_Algorithm_Rating_Quality_Param`) ON U)
    at org.jooq.impl.Utils.translate(Utils.java:1690)
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
    at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:133)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.AlgorithmOperations.lambda$storeRatingQualityAlgorithm$23(AlgorithmOperations.java:385)
    at org.jooq.impl.DefaultDSLContext$1.run(DefaultDSLContext.java:370)
    at org.jooq.impl.DefaultDSLContext$1.run(DefaultDSLContext.java:367)
    at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:339)
    at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:367)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.AlgorithmOperations.storeRatingQualityAlgorithm(AlgorithmOperations.java:381)
    at edu.kit.ipd.crowdcontrol.objectservice.quality.QualityIdentificator.lambda$new$1(QualityIdentificator.java:78)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at edu.kit.ipd.crowdcontrol.objectservice.quality.QualityIdentificator.<init>(QualityIdentificator.java:78)
    at edu.kit.ipd.crowdcontrol.objectservice.Main.boot(Main.java:120)
    at edu.kit.ipd.crowdcontrol.objectservice.Main.main(Main.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`crowdcontrol`.`Chosen_Rating_Quality_Param`, CONSTRAINT `chosenRatingQualityParam` FOREIGN KEY (`param`) REFERENCES `Algorithm_Rating_Quality_Param` (`id_Algorithm_Rating_Quality_Param`) ON U)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:932)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:410)
    at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:284)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
    ... 17 more

when starting

**Comment by lckr** [comment]
@LeanderK  Emtpy list for nonexistend parameters need to be respected in the algorithmOperations.storeRatingQualityAlgorithm()

**Comment by LeanderK** [comment]
the problem here is that we currently do not support database-migration between different version. An old version of the parameter is used in the system (or it changed from having one to zero), so i can't delete it without  possibly deleting whole experiments by accident. This is more complicated than it looks and should not occur in production systems, so the priority of fixing this is very low.
