### ISSUE TITLE
When a experiment is stopped.

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#188]
``` java
rx.exceptions.OnErrorNotImplementedException: SQL [select `crowdcontrol`.`Worker`.`id_worker`, `crowdcontrol`.`Worker`.`identification`, `crowdcontrol`.`Worker`.`platform`, `crowdcontrol`.`Worker`.`email`, `crowdcontrol`.`Worker`.`quality`, count(`crowdcontrol`.`Rating`.`id_rating`) as `count` from `crowdcontrol`.`Worker` right outer join `crowdcontrol`.`Rating` on `crowdcontrol`.`Rating`.`worker_id` = `crowdcontrol`.`Worker`.`id_worker` where (`crowdcontrol`.`Answer`.`experiment` = ? and `crowdcontrol`.`Answer`.`quality` >= ?) group by `crowdcontrol`.`Worker`.`id_worker`, `crowdcontrol`.`Worker`.`identification`, `crowdcontrol`.`Worker`.`platform`, `crowdcontrol`.`Worker`.`email`, `crowdcontrol`.`Worker`.`quality`]; Unknown column 'crowdcontrol.Answer.experiment' in 'where clause'
    at rx.Observable$27.onError(Observable.java:7923)
    at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:159)
    at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:146)
    at edu.kit.ipd.crowdcontrol.objectservice.event.EventObservable.eventEmit(EventObservable.java:40)
    at edu.kit.ipd.crowdcontrol.objectservice.event.EventObservable.lambda$emit$1(EventObservable.java:34)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at edu.kit.ipd.crowdcontrol.objectservice.event.EventObservable.emit(EventObservable.java:35)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.endExperiment(ExperimentResource.java:119)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.DEBUG(ExperimentResource.java:622)
    at edu.kit.ipd.crowdcontrol.objectservice.Main.boot(Main.java:234)
    at edu.kit.ipd.crowdcontrol.objectservice.Main.main(Main.java:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.jooq.exception.DataAccessException: SQL [select `crowdcontrol`.`Worker`.`id_worker`, `crowdcontrol`.`Worker`.`identification`, `crowdcontrol`.`Worker`.`platform`, `crowdcontrol`.`Worker`.`email`, `crowdcontrol`.`Worker`.`quality`, count(`crowdcontrol`.`Rating`.`id_rating`) as `count` from `crowdcontrol`.`Worker` right outer join `crowdcontrol`.`Rating` on `crowdcontrol`.`Rating`.`worker_id` = `crowdcontrol`.`Worker`.`id_worker` where (`crowdcontrol`.`Answer`.`experiment` = ? and `crowdcontrol`.`Answer`.`quality` >= ?) group by `crowdcontrol`.`Worker`.`id_worker`, `crowdcontrol`.`Worker`.`identification`, `crowdcontrol`.`Worker`.`platform`, `crowdcontrol`.`Worker`.`email`, `crowdcontrol`.`Worker`.`quality`]; Unknown column 'crowdcontrol.Answer.experiment' in 'where clause'
    at org.jooq.impl.Utils.translate(Utils.java:1690)
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
    at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:305)
    at org.jooq.impl.AbstractResultQuery.fetchMap(AbstractResultQuery.java:906)
    at org.jooq.impl.SelectImpl.fetchMap(SelectImpl.java:3127)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.AnswerRatingOperations.getNumOfGoodRatingsOfExperiment(AnswerRatingOperations.java:146)
    at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentCalculator.estimatePayment(PaymentCalculator.java:63)
    at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.dispatchPayment(PaymentDispatcher.java:56)
    at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.lambda$new$0(PaymentDispatcher.java:41)
    at rx.Observable$27.onNext(Observable.java:7928)
    at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
    ... 19 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'crowdcontrol.Answer.experiment' in 'where clause'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
    at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
    ... 28 more
```

**Comment by LeanderK** [comment]
fix can be merged after #184 is in master
