### ISSUE TITLE
Lisiting experiments

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#189]
``` java
15:11:22.227 [qtp1967060987-23] ERROR edu.kit.ipd.crowdcontrol.objectservice.rest.Router - an unknown exception occurred org.jooq.exception.DataAccessException: SQL [select `crowdcontrol`.`Rating_Constraint`.`id_rating_Constraints`, `crowdcontrol`.`Rating_Constraint`.`ref_rating`, `crowdcontrol`.`Rating_Constraint`.`off_constraint` from `crowdcontrol`.`Rating_Constraint` where (`crowdcontrol`.`Rating_Constraint`.`ref_rating` = ? and `crowdcontrol`.`Rating`.`rating` is not null)]; Unknown column 'crowdcontrol.Rating.rating' in 'where clause'
    at org.jooq.impl.Utils.translate(Utils.java:1690)
    at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
    at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:305)
    at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2577)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.AnswerRatingOperations.lambda$getRatings$12(AnswerRatingOperations.java:405)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:891)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.AnswerRatingOperations.getRatings(AnswerRatingOperations.java:412)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.AnswerRatingResource.lambda$getAnswers$0(AnswerRatingResource.java:64)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at edu.kit.ipd.crowdcontrol.objectservice.database.operations.Range.map(Range.java:115)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.AnswerRatingResource.getAnswers(AnswerRatingResource.java:63)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:57)
    at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:27)
    at spark.RouteImpl$1.handle(RouteImpl.java:58)
    at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
    at spark.webserver.JettyHandler.doHandle(JettyHandler.java:61)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'crowdcontrol.Rating.rating' in 'where clause'
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
    at com.mysql.jdbc.Util.getInstance(Util.java:387)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
    at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:262)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
    ... 41 more
```

**Comment by LeanderK** [comment]
fixed with b26b2f5c8503a55955919feeded483f21c9e9f2e
