### ISSUE TITLE
Publishing experiment fails

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#205]
```
Mär 14 14:59:00 edoras java[25728]: 14:59:00.161 [qtp564515203-25] ERROR edu.kit.ipd.crowdcontrol.objectservice.rest.Router - an unknown exception occurred java.lang.NullPointerException
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.template.Template.apply(Template.java:94)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.crowdworking.mturk.MturkPlatform.publishTask(MturkPlatform.java:124)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.crowdworking.PlatformManager.publishTask(PlatformManager.java:176)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.startExperiment(ExperimentResource.java:83)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.updateExperimentState(ExperimentResource.java:572)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.patch(ExperimentResource.java:370)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:56)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:27)
Mär 14 14:59:00 edoras java[25728]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.InputTransformer.handle(InputTransformer.java:80)
```

**Comment by LeanderK** [comment]
♥ NPE

**Comment by kelunik** [comment]
Configuration issue with `workerUIPublic` not set.
