### ISSUE TITLE
Crash when payment should happen

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#225]
```
objectservice_1 | Caused by: java.lang.NullPointerException
objectservice_1 |       at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentCalculator.estimatePayment(PaymentCalculator.java:67)
objectservice_1 |       at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.dispatchPayment(PaymentDispatcher.java:64)
objectservice_1 |       at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.lambda$new$0(PaymentDispatcher.java:48)
objectservice_1 |       at rx.Observable$27.onNext(Observable.java:7928)
objectservice_1 |       at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
objectservice_1 |       ... 47 more
```

**Comment by marcelhollerbach** [comment]
Integer in line 67 is NULL.

**Comment by LeanderK** [comment]
NUUUUUULLLLLL

**Comment by marcelhollerbach** [comment]
NUUUUUUUUUUULLLLL !!!
ноль !!!!
