### ISSUE TITLE
Platform Modes Read

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#240]
Without any platforms specified, all platforms are now enabled by default for a new experiment.

![image](https://cloud.githubusercontent.com/assets/2743004/13819493/f51b206c-eb99-11e5-8179-520a90484fea.png)

**Comment by kelunik** [comment]
```
Mär 16 17:14:11 edoras java[4598]: 17:14:11.262 [qtp57179685-21] ERROR edu.kit.ipd.crowdcontrol.objectservice.rest.Router - an unknown exception occurred org.jooq.exception.InvalidResultException: Key 3 is not unique in Result for +------+--------------------+---------------------+-
Mär 16 17:14:11 edoras java[4598]: |mode  |experiments_platform|max                  |platform          |
Mär 16 17:14:11 edoras java[4598]: +------+--------------------+---------------------+------------------+
Mär 16 17:14:11 edoras java[4598]: |rating|                   7|2016-03-16 17:14:11.0|dummydummy        |
Mär 16 17:14:11 edoras java[4598]: |answer|                   8|2016-03-16 17:08:32.0|mturkamazonsandbox|
Mär 16 17:14:11 edoras java[4598]: |normal|                   8|2016-03-16 17:14:11.0|mturkamazonsandbox|
Mär 16 17:14:11 edoras java[4598]: +------+--------------------+---------------------+------------------+
Mär 16 17:14:11 edoras java[4598]: at org.jooq.impl.ResultImpl.intoMap0(ResultImpl.java:1237)
Mär 16 17:14:11 edoras java[4598]: at org.jooq.impl.ResultImpl.intoMap(ResultImpl.java:1214)
Mär 16 17:14:11 edoras java[4598]: at org.jooq.impl.AbstractResultQuery.fetchMap(AbstractResultQuery.java:746)
Mär 16 17:14:11 edoras java[4598]: at org.jooq.impl.SelectImpl.fetchMap(SelectImpl.java:2967)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.database.operations.ExperimentsPlatformOperations.getActivePlatforms(ExperimentsPlatformOperations.java:234)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.database.ExperimentFetcher.getPopulations(ExperimentFetcher.java:104)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.database.ExperimentFetcher.fetchExperiment(ExperimentFetcher.java:132)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.updateExperimentInfoDraftState(ExperimentResource.java:358)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.rest.resources.ExperimentResource.patch(ExperimentResource.java:204)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:56)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.OutputTransformer.handle(OutputTransformer.java:27)
Mär 16 17:14:11 edoras java[4598]: at edu.kit.ipd.crowdcontrol.objectservice.rest.transformer.InputTransformer.handle(InputTransformer.java:80)
```

**Comment by kelunik** [comment]
![image](https://cloud.githubusercontent.com/assets/2743004/13819648/9a6eae76-eb9a-11e5-8584-26e750fdcfb3.png)
