### ISSUE TITLE
FeedbackCreator/Template NPE

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/object-service#248]
```
Caused by: java.lang.NullPointerException
      at edu.kit.ipd.crowdcontrol.objectservice.template.Template.apply(Template.java:94)
      at edu.kit.ipd.crowdcontrol.objectservice.feedback.FeedbackCreator.getFeedback(FeedbackCreator.java:70)
      at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher$1.apply(PaymentDispatcher.java:74)
      at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher$1.apply(PaymentDispatcher.java:69)
      at java.util.stream.Collectors.lambda$mapping$8(Collectors.java:355)
      at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:909)
      at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
      at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
      at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
      at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.dispatchPayment(PaymentDispatcher.java:67)
      at edu.kit.ipd.crowdcontrol.objectservice.payment.PaymentDispatcher.lambda$new$0(PaymentDispatcher.java:49)
      at rx.Observable$27.onNext(Observable.java:7928)
      at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
```

**Comment by kelunik** [comment]
That's a `FeedbackCreator` bug. Anyway, I will still make the error message better instead of a NPE.

**Comment by kelunik** [comment]
See #249. Prints a helpful error message now. Bug in `FeedbackCreator` still has to be fixed.

**Comment by kelunik** [comment]
@marcelhollerbach  What did you do to encounter this exception?

**Comment by redalertexpert** [comment]
I need more information to fix this, especially when these line numbers are nonsense.
