### ISSUE TITLE
Notification Failure (SQL)

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/object-service#263]
```
Mär 18 12:40:19 edoras java[13309]: 12:40:19.119 [pool-5-thread-1] ERROR edu.kit.ipd.crowdcontrol.objectservice.notification.Notification - An exception occurred while checking or sending a notification. org.jooq.exception.DataAccessException: SQL [SELECT * FROM Experiment ORDER BY experiment_id DESC LIMIT 1]; Unknown column 'experiment_id' in 'order clause'
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.Tools.translate(Tools.java:1690)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:341)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:328)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.AbstractResultQuery.stream(AbstractResultQuery.java:322)
Mär 18 12:40:19 edoras java[13309]: at org.jooq.impl.DefaultDSLContext.fetchStream(DefaultDSLContext.java:591)
Mär 18 12:40:19 edoras java[13309]: at edu.kit.ipd.crowdcontrol.objectservice.database.operations.NotificationOperations.runReadOnlySQL(NotificationOperations.java:213)
Mär 18 12:40:19 edoras java[13309]: at edu.kit.ipd.crowdcontrol.objectservice.notification.SQLEmailNotificationPolicy.check(SQLEmailNotificationPolicy.java:63)
Mär 18 12:40:19 edoras java[13309]: at edu.kit.ipd.crowdcontrol.objectservice.notification.SQLEmailNotificationPolicy.check(SQLEmailNotificationPolicy.java:27)
Mär 18 12:40:19 edoras java[13309]: at edu.kit.ipd.crowdcontrol.objectservice.notification.NotificationPolicy.invoke(NotificationPolicy.java:25)
Mär 18 12:40:19 edoras java[13309]: at edu.kit.ipd.crowdcontrol.objectservice.notification.Notification.run(Notification.java:98)
```

This should be caught and an e-mail sent to the receivers.

**Comment by kelunik** [comment]
Should be fine closing, @phimonk?
