### ISSUE TITLE
Exception, when adding a giftcode

### ISSUE THREAD

**Issue by TheRittler** [coolcrowd/object-service#318]
Getting this error, when setting up db and adding a giftcode to the db.

```
org.jooq.exception.DataAccessException: SQL [insert into `crowdcontrol`.`Gift_Code` (`code`, `amount`) values (?, ?)]; Field 'currency' doesn't have a default value

  at org.jooq.impl.Tools.translate(Tools.java:1690)
  at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
  at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
  at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:177)
  at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:143)
  at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
  at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:139)
  at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:185)
  at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85)
  at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135)
  at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
  at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131)
  at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123)
  at edu.kit.ipd.crowdcontrol.objectservice.database.operations.WorkerBalanceOperations.addGiftCode(WorkerBalanceOperations.java:48)
  at edu.kit.ipd.crowdcontrol.objectservice.moneytransfer.MoneyTransferTest.setUp(MoneyTransferTest.java:51)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:497)
  at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.sql.SQLException: Field 'currency' doesn't have a default value
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
  at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
  at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
  at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
  at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
  at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
  at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
  at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:88)
  at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:349)
  at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
  ... 40 more
´´´
```

**Comment by kelunik** [comment]
You just have to add the currency here: https://github.com/coolcrowd/object-service/blob/master/src/main/java/edu/kit/ipd/crowdcontrol/objectservice/database/operations/WorkerBalanceOperations.java#L44 in the signature and to the record.
